Changing build type

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,78 +1,49 @@
 #!/usr/bin/env bash
-# bin/compile <build-dir> <cache-dir>
 
-# fail fast
-set -e
+####### Configure environment
 
-# debug
-# set -x
+set -o errexit    # always exit on error
+set -o errtrace   # trap errors in functions as well
+set -o pipefail   # don't ignore exit codes when piping output
+set -o posix      # more strict failures in subshells
+# set -x          # enable debugging
 
-# parse and derive params
-BUILD_DIR=$1
-CACHE_DIR=$2
-ENV_DIR=$3
+# Configure directories
+build_dir=$1
+cache_dir=$2
+env_dir=$3
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
+heroku_dir=$build_dir/.heroku
+mkdir -p $heroku_dir/node
+warnings=$(mktemp)
 
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
+# Load dependencies
+source $bp_dir/lib/build.sh
 
-function error() {
-  echo " !     $*" >&2
-  exit 1
-}
+# Avoid GIT_DIR leak from previous build steps
+unset GIT_DIR
 
-function topic() {
-  echo "-----> $*"
-}
+# Provide hook to deal with errors
+trap build_failed ERR
 
-function indent() {
-  c='s/^/       /'
-  case $(uname) in
-    Darwin) sed -l "$c";;
-    *)      sed -u "$c";;
-  esac
-}
+####### Vendor in binaries
 
-PACKAGES="libssl1.0-dev nodejs nodejs-dev node-gyp npm"
+head "Installing binaries"
+install_node "12.17.0"
+install_npm
+install_serverless
 
-APT_CACHE_DIR="$CACHE_DIR/apt/cache"
-APT_STATE_DIR="$CACHE_DIR/apt/state"
+####### Create the profile
 
-mkdir -p "$APT_CACHE_DIR/archives/partial"
-mkdir -p "$APT_STATE_DIR/lists/partial"
+head "Creating profile"
+write_profile
+write_export
 
-APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
+####### Finalize the build
 
-case "$STACK" in
-  "cedar-14")
-    APT_FLAGS="--force-yes"
-    ;;
-  "heroku-16" | "heroku-18" | "heroku-20")
-    APT_FLAGS="--allow-downgrades --allow-remove-essential --allow-change-held-packages"
-    ;;
-  *)
-    error "STACK must be 'cedar-14', 'heroku-16', or 'heroku-18'"
-esac
+head "Finalizing build"
 
-topic "Updating apt caches"
-apt-get $APT_OPTIONS update | indent
-
-for PACKAGE in $PACKAGES; do
-  if [[ $PACKAGE == *deb ]]; then
-    PACKAGE_NAME=$(basename $PACKAGE .deb)
-    PACKAGE_FILE=$APT_CACHE_DIR/archives/$PACKAGE_NAME.deb
-
-    topic "Fetching $PACKAGE"
-    curl -s -L -z $PACKAGE_FILE -o $PACKAGE_FILE $PACKAGE 2>&1 | indent
-  else
-    topic "Fetching .debs for $PACKAGE"
-    apt-get $APT_OPTIONS -y $APT_FLAGS -d install --reinstall $PACKAGE | indent
-  fi
-done
-
-mkdir -p $BUILD_DIR/.apt
-
-for DEB in $(ls -1 $APT_CACHE_DIR/archives/*.deb); do
-  topic "Installing $(basename $DEB)"
-  dpkg -x $DEB $BUILD_DIR/.apt/
-done
-
-npm install -g serverless
+clean_npm
+clean_cache
+create_cache
+build_succeeded
